/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeclockRouteImport } from './routes/timeclock'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScopeSequenceRouteImport } from './routes/scope-sequence'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as IepsRouteImport } from './routes/ieps'
import { Route as HandoverRouteImport } from './routes/handover'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BehaviourRouteImport } from './routes/behaviour'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as AskIndexRouteImport } from './routes/ask.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherSsgMinutesRouteImport } from './routes/teacher.ssg-minutes'
import { Route as TeacherLoginRouteImport } from './routes/teacher.login'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as LessonsPlannerRouteImport } from './routes/lessons.planner'
import { Route as LessonsBankRouteImport } from './routes/lessons.bank'
import { Route as DevcheckBehaviourRouteImport } from './routes/devcheck.behaviour'
import { Route as AskThreadIdRouteImport } from './routes/ask.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminYearSetupRouteImport } from './routes/admin.year-setup'
import { Route as AdminWellbeingRouteImport } from './routes/admin.wellbeing'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminTimeclockRouteImport } from './routes/admin.timeclock'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSsgMinutesRouteImport } from './routes/admin.ssg-minutes'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRemindersRouteImport } from './routes/admin.reminders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminIepsRouteImport } from './routes/admin.ieps'
import { Route as AdminEvidenceRouteImport } from './routes/admin.evidence'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminCurriculumRouteImport } from './routes/admin.curriculum'
import { Route as AdminCrosscheckBuilderRouteImport } from './routes/admin.crosscheck-builder'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminBehaviourRouteImport } from './routes/admin.behaviour'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAlliedHealthRouteImport } from './routes/admin.allied-health'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as IepsGoalIdPrintRouteImport } from './routes/ieps.$goalId.print'

const TimeclockRoute = TimeclockRouteImport.update({
  id: '/timeclock',
  path: '/timeclock',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeSequenceRoute = ScopeSequenceRouteImport.update({
  id: '/scope-sequence',
  path: '/scope-sequence',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const IepsRoute = IepsRouteImport.update({
  id: '/ieps',
  path: '/ieps',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoverRoute = HandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BehaviourRoute = BehaviourRouteImport.update({
  id: '/behaviour',
  path: '/behaviour',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonsRoute,
} as any)
const AskIndexRoute = AskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AskRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSsgMinutesRoute = TeacherSsgMinutesRouteImport.update({
  id: '/teacher/ssg-minutes',
  path: '/teacher/ssg-minutes',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLoginRoute = TeacherLoginRouteImport.update({
  id: '/teacher/login',
  path: '/teacher/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentsRoute,
} as any)
const LessonsPlannerRoute = LessonsPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsBankRoute = LessonsBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => LessonsRoute,
} as any)
const DevcheckBehaviourRoute = DevcheckBehaviourRouteImport.update({
  id: '/devcheck/behaviour',
  path: '/devcheck/behaviour',
  getParentRoute: () => rootRouteImport,
} as any)
const AskThreadIdRoute = AskThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AskRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYearSetupRoute = AdminYearSetupRouteImport.update({
  id: '/admin/year-setup',
  path: '/admin/year-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWellbeingRoute = AdminWellbeingRouteImport.update({
  id: '/admin/wellbeing',
  path: '/admin/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/admin/timetable',
  path: '/admin/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimeclockRoute = AdminTimeclockRouteImport.update({
  id: '/admin/timeclock',
  path: '/admin/timeclock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSsgMinutesRoute = AdminSsgMinutesRouteImport.update({
  id: '/admin/ssg-minutes',
  path: '/admin/ssg-minutes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/admin/resources',
  path: '/admin/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRemindersRoute = AdminRemindersRouteImport.update({
  id: '/admin/reminders',
  path: '/admin/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIepsRoute = AdminIepsRouteImport.update({
  id: '/admin/ieps',
  path: '/admin/ieps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvidenceRoute = AdminEvidenceRouteImport.update({
  id: '/admin/evidence',
  path: '/admin/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurriculumRoute = AdminCurriculumRouteImport.update({
  id: '/admin/curriculum',
  path: '/admin/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrosscheckBuilderRoute = AdminCrosscheckBuilderRouteImport.update({
  id: '/admin/crosscheck-builder',
  path: '/admin/crosscheck-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/admin/classes',
  path: '/admin/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBehaviourRoute = AdminBehaviourRouteImport.update({
  id: '/admin/behaviour',
  path: '/admin/behaviour',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlliedHealthRoute = AdminAlliedHealthRouteImport.update({
  id: '/admin/allied-health',
  path: '/admin/allied-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IepsGoalIdPrintRoute = IepsGoalIdPrintRouteImport.update({
  id: '/$goalId/print',
  path: '/$goalId/print',
  getParentRoute: () => IepsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/behaviour': typeof BehaviourRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/handover': typeof HandoverRoute
  '/ieps': typeof IepsRouteWithChildren
  '/lessons': typeof LessonsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/parent': typeof ParentRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/scope-sequence': typeof ScopeSequenceRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRouteWithChildren
  '/timeclock': typeof TimeclockRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/allied-health': typeof AdminAlliedHealthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/behaviour': typeof AdminBehaviourRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/crosscheck-builder': typeof AdminCrosscheckBuilderRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/evidence': typeof AdminEvidenceRoute
  '/admin/ieps': typeof AdminIepsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/ssg-minutes': typeof AdminSsgMinutesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/timeclock': typeof AdminTimeclockRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellbeing': typeof AdminWellbeingRoute
  '/admin/year-setup': typeof AdminYearSetupRoute
  '/api/chat': typeof ApiChatRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/devcheck/behaviour': typeof DevcheckBehaviourRoute
  '/lessons/bank': typeof LessonsBankRoute
  '/lessons/planner': typeof LessonsPlannerRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/ssg-minutes': typeof TeacherSsgMinutesRoute
  '/admin/': typeof AdminIndexRoute
  '/ask/': typeof AskIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/ieps/$goalId/print': typeof IepsGoalIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/behaviour': typeof BehaviourRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/handover': typeof HandoverRoute
  '/ieps': typeof IepsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/parent': typeof ParentRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/scope-sequence': typeof ScopeSequenceRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRouteWithChildren
  '/timeclock': typeof TimeclockRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/allied-health': typeof AdminAlliedHealthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/behaviour': typeof AdminBehaviourRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/crosscheck-builder': typeof AdminCrosscheckBuilderRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/evidence': typeof AdminEvidenceRoute
  '/admin/ieps': typeof AdminIepsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/ssg-minutes': typeof AdminSsgMinutesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/timeclock': typeof AdminTimeclockRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellbeing': typeof AdminWellbeingRoute
  '/admin/year-setup': typeof AdminYearSetupRoute
  '/api/chat': typeof ApiChatRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/devcheck/behaviour': typeof DevcheckBehaviourRoute
  '/lessons/bank': typeof LessonsBankRoute
  '/lessons/planner': typeof LessonsPlannerRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/ssg-minutes': typeof TeacherSsgMinutesRoute
  '/admin': typeof AdminIndexRoute
  '/ask': typeof AskIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/ieps/$goalId/print': typeof IepsGoalIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/behaviour': typeof BehaviourRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/handover': typeof HandoverRoute
  '/ieps': typeof IepsRouteWithChildren
  '/lessons': typeof LessonsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/parent': typeof ParentRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/scope-sequence': typeof ScopeSequenceRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRouteWithChildren
  '/timeclock': typeof TimeclockRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/allied-health': typeof AdminAlliedHealthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/behaviour': typeof AdminBehaviourRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/crosscheck-builder': typeof AdminCrosscheckBuilderRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/evidence': typeof AdminEvidenceRoute
  '/admin/ieps': typeof AdminIepsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/ssg-minutes': typeof AdminSsgMinutesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/timeclock': typeof AdminTimeclockRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellbeing': typeof AdminWellbeingRoute
  '/admin/year-setup': typeof AdminYearSetupRoute
  '/api/chat': typeof ApiChatRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/devcheck/behaviour': typeof DevcheckBehaviourRoute
  '/lessons/bank': typeof LessonsBankRoute
  '/lessons/planner': typeof LessonsPlannerRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/ssg-minutes': typeof TeacherSsgMinutesRoute
  '/admin/': typeof AdminIndexRoute
  '/ask/': typeof AskIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/ieps/$goalId/print': typeof IepsGoalIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/attendance'
    | '/auth'
    | '/behaviour'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/evidence'
    | '/handover'
    | '/ieps'
    | '/lessons'
    | '/notifications'
    | '/parent'
    | '/pricing'
    | '/reports'
    | '/resources'
    | '/scope-sequence'
    | '/search'
    | '/settings'
    | '/students'
    | '/timeclock'
    | '/admin/activity'
    | '/admin/allied-health'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/behaviour'
    | '/admin/classes'
    | '/admin/crosscheck-builder'
    | '/admin/curriculum'
    | '/admin/documents'
    | '/admin/evidence'
    | '/admin/ieps'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/reminders'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/ssg-minutes'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/templates'
    | '/admin/timeclock'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin/wellbeing'
    | '/admin/year-setup'
    | '/api/chat'
    | '/ask/$threadId'
    | '/devcheck/behaviour'
    | '/lessons/bank'
    | '/lessons/planner'
    | '/students/$studentId'
    | '/teacher/login'
    | '/teacher/ssg-minutes'
    | '/admin/'
    | '/ask/'
    | '/lessons/'
    | '/ieps/$goalId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/auth'
    | '/behaviour'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/evidence'
    | '/handover'
    | '/ieps'
    | '/notifications'
    | '/parent'
    | '/pricing'
    | '/reports'
    | '/resources'
    | '/scope-sequence'
    | '/search'
    | '/settings'
    | '/students'
    | '/timeclock'
    | '/admin/activity'
    | '/admin/allied-health'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/behaviour'
    | '/admin/classes'
    | '/admin/crosscheck-builder'
    | '/admin/curriculum'
    | '/admin/documents'
    | '/admin/evidence'
    | '/admin/ieps'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/reminders'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/ssg-minutes'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/templates'
    | '/admin/timeclock'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin/wellbeing'
    | '/admin/year-setup'
    | '/api/chat'
    | '/ask/$threadId'
    | '/devcheck/behaviour'
    | '/lessons/bank'
    | '/lessons/planner'
    | '/students/$studentId'
    | '/teacher/login'
    | '/teacher/ssg-minutes'
    | '/admin'
    | '/ask'
    | '/lessons'
    | '/ieps/$goalId/print'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/attendance'
    | '/auth'
    | '/behaviour'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/evidence'
    | '/handover'
    | '/ieps'
    | '/lessons'
    | '/notifications'
    | '/parent'
    | '/pricing'
    | '/reports'
    | '/resources'
    | '/scope-sequence'
    | '/search'
    | '/settings'
    | '/students'
    | '/timeclock'
    | '/admin/activity'
    | '/admin/allied-health'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/behaviour'
    | '/admin/classes'
    | '/admin/crosscheck-builder'
    | '/admin/curriculum'
    | '/admin/documents'
    | '/admin/evidence'
    | '/admin/ieps'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/reminders'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/ssg-minutes'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/templates'
    | '/admin/timeclock'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin/wellbeing'
    | '/admin/year-setup'
    | '/api/chat'
    | '/ask/$threadId'
    | '/devcheck/behaviour'
    | '/lessons/bank'
    | '/lessons/planner'
    | '/students/$studentId'
    | '/teacher/login'
    | '/teacher/ssg-minutes'
    | '/admin/'
    | '/ask/'
    | '/lessons/'
    | '/ieps/$goalId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRouteWithChildren
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  BehaviourRoute: typeof BehaviourRoute
  CalendarRoute: typeof CalendarRoute
  ClassesRoute: typeof ClassesRoute
  DashboardRoute: typeof DashboardRoute
  EvidenceRoute: typeof EvidenceRoute
  HandoverRoute: typeof HandoverRoute
  IepsRoute: typeof IepsRouteWithChildren
  LessonsRoute: typeof LessonsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ParentRoute: typeof ParentRoute
  PricingRoute: typeof PricingRoute
  ReportsRoute: typeof ReportsRoute
  ResourcesRoute: typeof ResourcesRoute
  ScopeSequenceRoute: typeof ScopeSequenceRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  TimeclockRoute: typeof TimeclockRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAlliedHealthRoute: typeof AdminAlliedHealthRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBehaviourRoute: typeof AdminBehaviourRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminCrosscheckBuilderRoute: typeof AdminCrosscheckBuilderRoute
  AdminCurriculumRoute: typeof AdminCurriculumRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminEvidenceRoute: typeof AdminEvidenceRoute
  AdminIepsRoute: typeof AdminIepsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRemindersRoute: typeof AdminRemindersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSsgMinutesRoute: typeof AdminSsgMinutesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminTimeclockRoute: typeof AdminTimeclockRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWellbeingRoute: typeof AdminWellbeingRoute
  AdminYearSetupRoute: typeof AdminYearSetupRoute
  ApiChatRoute: typeof ApiChatRoute
  DevcheckBehaviourRoute: typeof DevcheckBehaviourRoute
  TeacherLoginRoute: typeof TeacherLoginRoute
  TeacherSsgMinutesRoute: typeof TeacherSsgMinutesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeclock': {
      id: '/timeclock'
      path: '/timeclock'
      fullPath: '/timeclock'
      preLoaderRoute: typeof TimeclockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope-sequence': {
      id: '/scope-sequence'
      path: '/scope-sequence'
      fullPath: '/scope-sequence'
      preLoaderRoute: typeof ScopeSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ieps': {
      id: '/ieps'
      path: '/ieps'
      fullPath: '/ieps'
      preLoaderRoute: typeof IepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handover': {
      id: '/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof HandoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behaviour': {
      id: '/behaviour'
      path: '/behaviour'
      fullPath: '/behaviour'
      preLoaderRoute: typeof BehaviourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/ask/': {
      id: '/ask/'
      path: '/'
      fullPath: '/ask/'
      preLoaderRoute: typeof AskIndexRouteImport
      parentRoute: typeof AskRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/ssg-minutes': {
      id: '/teacher/ssg-minutes'
      path: '/teacher/ssg-minutes'
      fullPath: '/teacher/ssg-minutes'
      preLoaderRoute: typeof TeacherSsgMinutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/login': {
      id: '/teacher/login'
      path: '/teacher/login'
      fullPath: '/teacher/login'
      preLoaderRoute: typeof TeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/lessons/planner': {
      id: '/lessons/planner'
      path: '/planner'
      fullPath: '/lessons/planner'
      preLoaderRoute: typeof LessonsPlannerRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/bank': {
      id: '/lessons/bank'
      path: '/bank'
      fullPath: '/lessons/bank'
      preLoaderRoute: typeof LessonsBankRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/devcheck/behaviour': {
      id: '/devcheck/behaviour'
      path: '/devcheck/behaviour'
      fullPath: '/devcheck/behaviour'
      preLoaderRoute: typeof DevcheckBehaviourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/$threadId': {
      id: '/ask/$threadId'
      path: '/$threadId'
      fullPath: '/ask/$threadId'
      preLoaderRoute: typeof AskThreadIdRouteImport
      parentRoute: typeof AskRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/year-setup': {
      id: '/admin/year-setup'
      path: '/admin/year-setup'
      fullPath: '/admin/year-setup'
      preLoaderRoute: typeof AdminYearSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wellbeing': {
      id: '/admin/wellbeing'
      path: '/admin/wellbeing'
      fullPath: '/admin/wellbeing'
      preLoaderRoute: typeof AdminWellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/admin/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timeclock': {
      id: '/admin/timeclock'
      path: '/admin/timeclock'
      fullPath: '/admin/timeclock'
      preLoaderRoute: typeof AdminTimeclockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ssg-minutes': {
      id: '/admin/ssg-minutes'
      path: '/admin/ssg-minutes'
      fullPath: '/admin/ssg-minutes'
      preLoaderRoute: typeof AdminSsgMinutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/admin/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reminders': {
      id: '/admin/reminders'
      path: '/admin/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AdminRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ieps': {
      id: '/admin/ieps'
      path: '/admin/ieps'
      fullPath: '/admin/ieps'
      preLoaderRoute: typeof AdminIepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evidence': {
      id: '/admin/evidence'
      path: '/admin/evidence'
      fullPath: '/admin/evidence'
      preLoaderRoute: typeof AdminEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/curriculum': {
      id: '/admin/curriculum'
      path: '/admin/curriculum'
      fullPath: '/admin/curriculum'
      preLoaderRoute: typeof AdminCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crosscheck-builder': {
      id: '/admin/crosscheck-builder'
      path: '/admin/crosscheck-builder'
      fullPath: '/admin/crosscheck-builder'
      preLoaderRoute: typeof AdminCrosscheckBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/admin/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/behaviour': {
      id: '/admin/behaviour'
      path: '/admin/behaviour'
      fullPath: '/admin/behaviour'
      preLoaderRoute: typeof AdminBehaviourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/allied-health': {
      id: '/admin/allied-health'
      path: '/admin/allied-health'
      fullPath: '/admin/allied-health'
      preLoaderRoute: typeof AdminAlliedHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ieps/$goalId/print': {
      id: '/ieps/$goalId/print'
      path: '/$goalId/print'
      fullPath: '/ieps/$goalId/print'
      preLoaderRoute: typeof IepsGoalIdPrintRouteImport
      parentRoute: typeof IepsRoute
    }
  }
}

interface AskRouteChildren {
  AskThreadIdRoute: typeof AskThreadIdRoute
  AskIndexRoute: typeof AskIndexRoute
}

const AskRouteChildren: AskRouteChildren = {
  AskThreadIdRoute: AskThreadIdRoute,
  AskIndexRoute: AskIndexRoute,
}

const AskRouteWithChildren = AskRoute._addFileChildren(AskRouteChildren)

interface IepsRouteChildren {
  IepsGoalIdPrintRoute: typeof IepsGoalIdPrintRoute
}

const IepsRouteChildren: IepsRouteChildren = {
  IepsGoalIdPrintRoute: IepsGoalIdPrintRoute,
}

const IepsRouteWithChildren = IepsRoute._addFileChildren(IepsRouteChildren)

interface LessonsRouteChildren {
  LessonsBankRoute: typeof LessonsBankRoute
  LessonsPlannerRoute: typeof LessonsPlannerRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsBankRoute: LessonsBankRoute,
  LessonsPlannerRoute: LessonsPlannerRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

interface StudentsRouteChildren {
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsStudentIdRoute: StudentsStudentIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  BehaviourRoute: BehaviourRoute,
  CalendarRoute: CalendarRoute,
  ClassesRoute: ClassesRoute,
  DashboardRoute: DashboardRoute,
  EvidenceRoute: EvidenceRoute,
  HandoverRoute: HandoverRoute,
  IepsRoute: IepsRouteWithChildren,
  LessonsRoute: LessonsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ParentRoute: ParentRoute,
  PricingRoute: PricingRoute,
  ReportsRoute: ReportsRoute,
  ResourcesRoute: ResourcesRoute,
  ScopeSequenceRoute: ScopeSequenceRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRouteWithChildren,
  TimeclockRoute: TimeclockRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAlliedHealthRoute: AdminAlliedHealthRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBehaviourRoute: AdminBehaviourRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminCrosscheckBuilderRoute: AdminCrosscheckBuilderRoute,
  AdminCurriculumRoute: AdminCurriculumRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminEvidenceRoute: AdminEvidenceRoute,
  AdminIepsRoute: AdminIepsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRemindersRoute: AdminRemindersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSsgMinutesRoute: AdminSsgMinutesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminTimeclockRoute: AdminTimeclockRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWellbeingRoute: AdminWellbeingRoute,
  AdminYearSetupRoute: AdminYearSetupRoute,
  ApiChatRoute: ApiChatRoute,
  DevcheckBehaviourRoute: DevcheckBehaviourRoute,
  TeacherLoginRoute: TeacherLoginRoute,
  TeacherSsgMinutesRoute: TeacherSsgMinutesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
