/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeclockRouteImport } from './routes/timeclock'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScopeSequenceRouteImport } from './routes/scope-sequence'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as IepsRouteImport } from './routes/ieps'
import { Route as HandoverRouteImport } from './routes/handover'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BehaviourRouteImport } from './routes/behaviour'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherLoginRouteImport } from './routes/teacher.login'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as AdminWellbeingRouteImport } from './routes/admin.wellbeing'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminTimeclockRouteImport } from './routes/admin.timeclock'
import { Route as AdminRemindersRouteImport } from './routes/admin.reminders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAlliedHealthRouteImport } from './routes/admin.allied-health'
import { Route as IepsGoalIdPrintRouteImport } from './routes/ieps.$goalId.print'

const TimeclockRoute = TimeclockRouteImport.update({
  id: '/timeclock',
  path: '/timeclock',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeSequenceRoute = ScopeSequenceRouteImport.update({
  id: '/scope-sequence',
  path: '/scope-sequence',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const IepsRoute = IepsRouteImport.update({
  id: '/ieps',
  path: '/ieps',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoverRoute = HandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BehaviourRoute = BehaviourRouteImport.update({
  id: '/behaviour',
  path: '/behaviour',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLoginRoute = TeacherLoginRouteImport.update({
  id: '/teacher/login',
  path: '/teacher/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentsRoute,
} as any)
const AdminWellbeingRoute = AdminWellbeingRouteImport.update({
  id: '/admin/wellbeing',
  path: '/admin/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/admin/timetable',
  path: '/admin/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimeclockRoute = AdminTimeclockRouteImport.update({
  id: '/admin/timeclock',
  path: '/admin/timeclock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRemindersRoute = AdminRemindersRouteImport.update({
  id: '/admin/reminders',
  path: '/admin/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlliedHealthRoute = AdminAlliedHealthRouteImport.update({
  id: '/admin/allied-health',
  path: '/admin/allied-health',
  getParentRoute: () => rootRouteImport,
} as any)
const IepsGoalIdPrintRoute = IepsGoalIdPrintRouteImport.update({
  id: '/$goalId/print',
  path: '/$goalId/print',
  getParentRoute: () => IepsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/behaviour': typeof BehaviourRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/handover': typeof HandoverRoute
  '/ieps': typeof IepsRouteWithChildren
  '/lessons': typeof LessonsRoute
  '/notifications': typeof NotificationsRoute
  '/parent': typeof ParentRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/scope-sequence': typeof ScopeSequenceRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRouteWithChildren
  '/timeclock': typeof TimeclockRoute
  '/admin/allied-health': typeof AdminAlliedHealthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/timeclock': typeof AdminTimeclockRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellbeing': typeof AdminWellbeingRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/ieps/$goalId/print': typeof IepsGoalIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/behaviour': typeof BehaviourRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/handover': typeof HandoverRoute
  '/ieps': typeof IepsRouteWithChildren
  '/lessons': typeof LessonsRoute
  '/notifications': typeof NotificationsRoute
  '/parent': typeof ParentRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/scope-sequence': typeof ScopeSequenceRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRouteWithChildren
  '/timeclock': typeof TimeclockRoute
  '/admin/allied-health': typeof AdminAlliedHealthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/timeclock': typeof AdminTimeclockRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellbeing': typeof AdminWellbeingRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/admin': typeof AdminIndexRoute
  '/ieps/$goalId/print': typeof IepsGoalIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/behaviour': typeof BehaviourRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/handover': typeof HandoverRoute
  '/ieps': typeof IepsRouteWithChildren
  '/lessons': typeof LessonsRoute
  '/notifications': typeof NotificationsRoute
  '/parent': typeof ParentRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/scope-sequence': typeof ScopeSequenceRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRouteWithChildren
  '/timeclock': typeof TimeclockRoute
  '/admin/allied-health': typeof AdminAlliedHealthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/timeclock': typeof AdminTimeclockRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellbeing': typeof AdminWellbeingRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/ieps/$goalId/print': typeof IepsGoalIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/behaviour'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/evidence'
    | '/handover'
    | '/ieps'
    | '/lessons'
    | '/notifications'
    | '/parent'
    | '/reports'
    | '/resources'
    | '/scope-sequence'
    | '/settings'
    | '/students'
    | '/timeclock'
    | '/admin/allied-health'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/login'
    | '/admin/reminders'
    | '/admin/timeclock'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin/wellbeing'
    | '/students/$studentId'
    | '/teacher/login'
    | '/admin/'
    | '/ieps/$goalId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/behaviour'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/evidence'
    | '/handover'
    | '/ieps'
    | '/lessons'
    | '/notifications'
    | '/parent'
    | '/reports'
    | '/resources'
    | '/scope-sequence'
    | '/settings'
    | '/students'
    | '/timeclock'
    | '/admin/allied-health'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/login'
    | '/admin/reminders'
    | '/admin/timeclock'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin/wellbeing'
    | '/students/$studentId'
    | '/teacher/login'
    | '/admin'
    | '/ieps/$goalId/print'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/behaviour'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/evidence'
    | '/handover'
    | '/ieps'
    | '/lessons'
    | '/notifications'
    | '/parent'
    | '/reports'
    | '/resources'
    | '/scope-sequence'
    | '/settings'
    | '/students'
    | '/timeclock'
    | '/admin/allied-health'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/login'
    | '/admin/reminders'
    | '/admin/timeclock'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin/wellbeing'
    | '/students/$studentId'
    | '/teacher/login'
    | '/admin/'
    | '/ieps/$goalId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BehaviourRoute: typeof BehaviourRoute
  CalendarRoute: typeof CalendarRoute
  ClassesRoute: typeof ClassesRoute
  DashboardRoute: typeof DashboardRoute
  EvidenceRoute: typeof EvidenceRoute
  HandoverRoute: typeof HandoverRoute
  IepsRoute: typeof IepsRouteWithChildren
  LessonsRoute: typeof LessonsRoute
  NotificationsRoute: typeof NotificationsRoute
  ParentRoute: typeof ParentRoute
  ReportsRoute: typeof ReportsRoute
  ResourcesRoute: typeof ResourcesRoute
  ScopeSequenceRoute: typeof ScopeSequenceRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  TimeclockRoute: typeof TimeclockRoute
  AdminAlliedHealthRoute: typeof AdminAlliedHealthRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRemindersRoute: typeof AdminRemindersRoute
  AdminTimeclockRoute: typeof AdminTimeclockRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWellbeingRoute: typeof AdminWellbeingRoute
  TeacherLoginRoute: typeof TeacherLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeclock': {
      id: '/timeclock'
      path: '/timeclock'
      fullPath: '/timeclock'
      preLoaderRoute: typeof TimeclockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope-sequence': {
      id: '/scope-sequence'
      path: '/scope-sequence'
      fullPath: '/scope-sequence'
      preLoaderRoute: typeof ScopeSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ieps': {
      id: '/ieps'
      path: '/ieps'
      fullPath: '/ieps'
      preLoaderRoute: typeof IepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handover': {
      id: '/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof HandoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behaviour': {
      id: '/behaviour'
      path: '/behaviour'
      fullPath: '/behaviour'
      preLoaderRoute: typeof BehaviourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/login': {
      id: '/teacher/login'
      path: '/teacher/login'
      fullPath: '/teacher/login'
      preLoaderRoute: typeof TeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/admin/wellbeing': {
      id: '/admin/wellbeing'
      path: '/admin/wellbeing'
      fullPath: '/admin/wellbeing'
      preLoaderRoute: typeof AdminWellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/admin/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/timeclock': {
      id: '/admin/timeclock'
      path: '/admin/timeclock'
      fullPath: '/admin/timeclock'
      preLoaderRoute: typeof AdminTimeclockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reminders': {
      id: '/admin/reminders'
      path: '/admin/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AdminRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/allied-health': {
      id: '/admin/allied-health'
      path: '/admin/allied-health'
      fullPath: '/admin/allied-health'
      preLoaderRoute: typeof AdminAlliedHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ieps/$goalId/print': {
      id: '/ieps/$goalId/print'
      path: '/$goalId/print'
      fullPath: '/ieps/$goalId/print'
      preLoaderRoute: typeof IepsGoalIdPrintRouteImport
      parentRoute: typeof IepsRoute
    }
  }
}

interface IepsRouteChildren {
  IepsGoalIdPrintRoute: typeof IepsGoalIdPrintRoute
}

const IepsRouteChildren: IepsRouteChildren = {
  IepsGoalIdPrintRoute: IepsGoalIdPrintRoute,
}

const IepsRouteWithChildren = IepsRoute._addFileChildren(IepsRouteChildren)

interface StudentsRouteChildren {
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsStudentIdRoute: StudentsStudentIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BehaviourRoute: BehaviourRoute,
  CalendarRoute: CalendarRoute,
  ClassesRoute: ClassesRoute,
  DashboardRoute: DashboardRoute,
  EvidenceRoute: EvidenceRoute,
  HandoverRoute: HandoverRoute,
  IepsRoute: IepsRouteWithChildren,
  LessonsRoute: LessonsRoute,
  NotificationsRoute: NotificationsRoute,
  ParentRoute: ParentRoute,
  ReportsRoute: ReportsRoute,
  ResourcesRoute: ResourcesRoute,
  ScopeSequenceRoute: ScopeSequenceRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRouteWithChildren,
  TimeclockRoute: TimeclockRoute,
  AdminAlliedHealthRoute: AdminAlliedHealthRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRemindersRoute: AdminRemindersRoute,
  AdminTimeclockRoute: AdminTimeclockRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWellbeingRoute: AdminWellbeingRoute,
  TeacherLoginRoute: TeacherLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
